spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_jwt
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    hostname: smtp-relay.brevo.com
    port: 587
    username: 797207001@smtp-brevo.com
    password: 7fGDbFNKgYZzcRMW
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect




