spring:
  datasource:
    url: jdbc:mysql://latzanc.ctskucikmx00.eu-central-1.rds.amazonaws.com:3306/latzanc
    username: latzanc_admin
    password: LaTzanc123!
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    hostname: smtp-relay.brevo.com
    port: 587
    username: 797207001@smtp-brevo.com
    password: 7fGDbFNKgYZzcRMW
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
  flyway:
    user: latzanc_admin
    password: LaTzanc123!
    schemas: latzanc
    url: jdbc:mysql://latzanc.ctskucikmx00.eu-central-1.rds.amazonaws.com:3306/latzanc
  originUrl: http://localhost:4200



